### ISSUE TITLE
liquibase.exception.DatabaseException: Invalid default value for 'created_on' [Failed SQL: ALTER TABLE meeting.sys_event_store MODIFY created_on timestamp(3) DEFAULT current_timestamp()

### ISSUE THREAD

**Issue by miricy** [eclipse-kapua/kapua#2991]
**Describe the bug**
I try it use database mysql 5.6, mysql 8.0.

all 1.2.0 database update liquibase file like below:

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.0.xsd"
        logicalFilePath="KapuaDB/changelog-event-store-1.2.0.xml">

    <include relativeToChangelogFile="true" file="../common-properties.xml"/>

    <changeSet id="changelog-event_store-1.2.0-timestamp" author="eurotech" dbms="mysql, mariadb" context="fixTimestamps">
        <modifyDataType tableName="sys_event_store" columnName="created_on" newDataType="timestamp(3) DEFAULT ${now}"/>
        <modifyDataType tableName="sys_event_store" columnName="modified_on" newDataType="timestamp(3) DEFAULT ${now}"/>
        <modifyDataType tableName="sys_event_store" columnName="event_on" newDataType="timestamp(3) DEFAULT ${now}"/>
    </changeSet>

</databaseChangeLog>

### liquibase excute has a exception.   timestamp(3)
When i modify timestamp(3) to timestamp and is ok.

Below is the exception info:

Reason: liquibase.exception.DatabaseException: Invalid default value for 'created_on' [Failed SQL: ALTER TABLE meeting.sys_event_store MODIFY created_on timestamp(3) DEFAULT current_timestamp()]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:168)
	at org.eclipse.kapua.commons.liquibase.KapuaLiquibaseClient.executeMasters(KapuaLiquibaseClient.java:224)
	at org.eclipse.kapua.commons.liquibase.KapuaLiquibaseClient.executeMasters(KapuaLiquibaseClient.java:196)
	at org.eclipse.kapua.commons.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:149)
	at org.eclipse.kapua.app.api.web.RestApiListener.contextInitialized(RestApiListener.java:59)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4579)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5041)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:987)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1858)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1586)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)

**To Reproduce**
1. update to 1.2.0
2. update the database

**Expected behavior**

**Version of Kapua**
[1.2.0]

**Type of deployment**
[*] Local Vagrant deployment
[ ] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ *] - Others

**Comment by Coduz** [comment]
Hi @miricy 

Sorry for the late response. 

The column should be Timestamp(3). 
Do you tried that on a fresh install or you upgraded from 1.1.x to 1.2.0? 

Regards, 

_Alberto_

**Comment by miricy** [comment]
@Coduz Thank you for your response, 
What's the 'timestamp(3)' mean in mysql,
Whether the default date is in this range.

**Comment by miricy** [comment]
I excute the sql script direct in mysql, but the error is also happen.
```sql
ALTER TABLE sys_event_store MODIFY created_on timestamp(3) DEFAULT current_timestamp();
```
the error is:
09:01:29	ALTER TABLE sys_event_store MODIFY created_on timestamp(3) DEFAULT current_timestamp()	Error Code: 1067. Invalid default value for 'created_on'	0.0027 sec

But modify timestamp(3) to timestamp is ok.

**Comment by Coduz** [comment]
Maybe this will fix the error but only get around the problem.

`TIMESTAMP(n)` identifies a column of type `TIMESTAMP` with `n` digits of precision.

So `TIMESTAMP(3)` identifies a `TIMESTAMP` column with millisecond precision. If, for example, we use `TIMESTAMP(6)` we will have a nanosecond precision. 

So if you use TIMESTAMP you'll loose the precision of that field, which can be critical in some places.

**Comment by miricy** [comment]
@Coduz Yes, you are right.
I think the problem is the default value 'current_timestamp()' can't auto cast to 'timestamp(3)'.

I excute " ALTER TABLE sys_event_store MODIFY created_on timestamp(3) DEFAULT current_timestamp(3); " in mysql,
and it's ok .

In the 'common-properties.xml' file, Can we modify
```
<property name="now" value="current_timestamp()" dbms="mysql,mariadb,h2"/>
```
to 
```
<property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
```
Below is the mysql document :
![image](https://user-images.githubusercontent.com/2841879/85974595-7a257000-ba08-11ea-89d9-72562ff4fdfc.png)

**Comment by Coduz** [comment]
Yes that would be a viable solution 😁  
Do you want to make the PR?
