### ISSUE TITLE
ES Migrator Fails 

### ISSUE THREAD

**Issue by swiftconnect** [eclipse-kapua/kapua#3221]
**Describe the bug**
ES Migrator Tool fails due to HTTP 400 Bad Request
The following is the stack trace printed on the console:
```java -cp kapua-es-migrator-1.5.0-SNAPSHOT-app.jar  org.eclipse.kapua.extras.esmigrator.^Cplication
swiftsense@new-kapua:~/kapua/extras/es-migrator/target$ java -cp kapua-es-migrator-1.5.0-SNAPSHOT-app.jar  org.eclipse.kapua.extras.esmigrator.Application
10:24:18.596 [main] INFO org.eclipse.kapua.extras.esmigrator.Application - Starting Elasticsearch Index Migration Tool
10:24:19.026 [main] DEBUG org.eclipse.kapua.commons.setting.AbstractKapuaSetting - Loaded configuration resource: 'es-migrator-setting.properties'
10:24:19.041 [main] INFO org.eclipse.kapua.extras.esmigrator.Migrator - Elasticsearch Cluster Address: http://localhost:9200
10:24:21.061 [main] DEBUG org.eclipse.kapua.extras.esmigrator.Migrator - Found 129 open indexes to be migrated
10:24:21.067 [main] INFO org.eclipse.kapua.extras.esmigrator.Migrator - Updating dates mapping for index 6323827499659459024-2020-25
Exception in thread "main" ElasticsearchStatusException[method [HEAD], host [http://localhost:9200], URI [/6323827499659459024-2020-25_tmp?ignore_throttled=false&include_type_name=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://localhost:9200], URI [/6323827499659459024-2020-25_tmp?ignore_throttled=false&include_type_name=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]]; nested: ResponseException[method [HEAD], host [http://localhost:9200], URI [/6323827499659459024-2020-25_tmp?ignore_throttled=false&include_type_name=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]];
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2027)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1749)
        at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:1087)
        at org.eclipse.kapua.extras.esmigrator.Migrator.updateMappingDates(Migrator.java:143)
        at org.eclipse.kapua.extras.esmigrator.Migrator.doMigrate(Migrator.java:127)
        at org.eclipse.kapua.extras.esmigrator.Application.main(Application.java:26)
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://localhost:9200], URI [/6323827499659459024-2020-25_tmp?ignore_throttled=false&include_type_name=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764)
        ... 5 more
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://localhost:9200], URI [/6323827499659459024-2020-25_tmp?ignore_throttled=false&include_type_name=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 400 Bad Request]
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:552)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:309)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**

- Clone and build kapua
- Navigate to extras/es-migrator/target
- Run the following command:  **java -cp kapua-es-migrator-1.5.0-SNAPSHOT-app.jar  org.eclipse.kapua.extras.esmigrator.Application**
- The process starts normally but then fails with the HTTP 400 errors

**Expected behavior**
The existing and open pre-6.8 indices for Kapua should be processed

**Screenshots**

**Version of Kapua**

commit e48e1384041e9d4fb5e4ba6da5123b61a666db22
Merge: 71f3aab 0db536c
Author: Alberto Codutti <Coduz@users.noreply.github.com>
Date:   Wed Jan 20 09:10:12 2021 +0100

**Type of deployment**
[ ] Docker

**Main component affected**
[ ] - Extras

**Additional context**
The documentation for the migrator tool is not complete especially around how to run the tool. Can work together to get this piece up and running

**Comment by lorthirk** [comment]
Is the tool running against an Elasticsearch 6 cluster?

**Comment by swiftconnect** [comment]
Yes Claudio - is that a problem?

**Comment by lorthirk** [comment]
No, it's how it is supposed to work actually. 

It would be great if you could have a log from the ES cluster, because in the Migration Tool log you won't find anything about the cause of the error.

**Comment by lorthirk** [comment]
Closed due to inactivity
