### ISSUE TITLE
Internal user InternalUsername fails with 'User not allowed' error when trying to get configuration through Devices Api

### ISSUE THREAD

**Issue by swiftconnect** [eclipse-kapua/kapua#3289]
**Describe the bug**
Calling the Kapua API for device configuration results in a 'User not allowed' based exception in the broker

**To Reproduce**

- Call the : **/v1/{scopeId}/devices/{deviceId}/configurations** using apikey for an admin level user
- Kapua API throws HTTP 500 error
- See below excerpt from the kapua stack traces:
`k1.4.3bro        | 06:33:57.645 [ActiveMQ NIO Worker 5] DEBUG o.a.a.b.TransportConnection.Service - Error occured while processing sync command: ConnectionInfo {commandId = 0, responseRequired = true, connectionId = ID:6ef6e1c0d152-38944-1617429952688-3:25, clientId = KapuaPool-1617431637020-1719729462833355409, clientIp = tcp://172.20.0.7:37310, userName = internalUsername, password = *****, brokerPath = null, brokerMasterConnector = false, manageable = false, clientMaster = true, faultTolerant = false, failoverReconnect = false}, exception: java.lang.SecurityException: User not allowed!
k1.4.3bro        | java.lang.SecurityException: User not allowed!
k1.4.3bro        |      at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addConnection(KapuaSecurityBrokerFilter.java:427)
k1.4.3bro        |      at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)
k1.4.3bro        |      at org.apache.activemq.broker.MutableBrokerFilter.addConnection(MutableBrokerFilter.java:103)
k1.4.3bro        |      at org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:852)
k1.4.3bro        |      at org.apache.activemq.broker.jmx.ManagedTransportConnection.processAddConnection(ManagedTransportConnection.java:77)
k1.4.3bro        |      at org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)
k1.4.3bro        |      at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
k1.4.3api        | 06:33:57.653 [qtp913190639-15] ERROR o.e.k.a.a.c.e.KapuaExceptionMapper - Generic Kapua exception!
k1.4.3api        | org.eclipse.kapua.service.device.management.exception.DeviceManagementSendException: An error occurred when sending the message: org.eclipse.kapua.service.device.management.configuration.message.internal.ConfigurationRequestMessage@54f8bac9
`

**Expected behavior**
All other calls to the Kapua API prior to this call succeed - and this one should succeed as well with default configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/69026265/113471690-a5a22300-9490-11eb-90af-a200457bbd6a.png)

**Version of Kapua**
1.4.3

**Type of deployment**
[* ] Docker

**Main component affected**
[ ] REST API

**Additional context**
Note that the external user making the call has Admin role and for good measure has also been given various other rights as well.
In the code 
From the code snippet in the screenshot I would expect that the internal user based call should have succeeded

**Comment by swiftconnect** [comment]
Cannot reproduce issue on locally built kapua system - closing
