### ISSUE TITLE
It seems necessary to use a privileged container to compile the project

### ISSUE THREAD

**Issue by jack9603301** [eclipse-kapua/kapua#3932]
**Describe the bug**
Due to customer requirements, I started using Docker on LXD for the client server and compiling and installing eclipse kapua in it.
stay https://github.com/eclipse/kapua/issues/3369 In the question, I was asked to compile the source code according to the following document:
https://github.com/eclipse/kapua/blob/a19266371b8113b384deebe11155e66170569bf7/docs/developer-guide/en/building.md#docker -Images
Currently compiling, however, I encountered the following error while compiling the container for jetty base:
```
useradd -u 1000 -g 0 -d '/var/opt/jetty' -s '/sbin/nologin' jetty &&     mkdir -p /opt/jetty /var/opt/jetty/lib/ext /var/opt/jetty/start.d /var/opt/jetty/tls &&     curl -Ls https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.12.v20180830/jetty-distribution-9.4.12.v20180830.tar.gz -o /tmp/jetty.tar.gz &&     tar --strip=1 -xzf /tmp/jetty.tar.gz -C /opt/jetty &&     rm -f /tmp/jetty.tar.gz &&     cd /var/opt/jetty &&     java -jar /opt/jetty/start.jar --approve-all-licenses --create-startd --add-to-start=http,https,jsp,jstl,websocket,deploy,logging-logback,jmx,ssl,stats &&     chown -R 1000:0 /opt/jetty /var/opt/jetty &&     chmod -R g=u /opt/jetty /var/opt/jetty
java.lang.ExceptionInInitializerError
        at sun.nio.ch.FileChannelImpl.<init>(FileChannelImpl.java:89)
        at sun.nio.ch.FileChannelImpl.open(FileChannelImpl.java:105)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:137)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at java.nio.file.Files.newBufferedReader(Files.java:2784)
        at org.eclipse.jetty.start.Module.process(Module.java:293)
        at org.eclipse.jetty.start.Module.<init>(Module.java:151)
        at org.eclipse.jetty.start.Modules.registerModule(Modules.java:208)
        at org.eclipse.jetty.start.Modules.registerAll(Modules.java:194)
        at org.eclipse.jetty.start.Main.processCommandLine(Main.java:314)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: java.io.IOException: Permission denied
        at sun.nio.ch.FileDispatcherImpl.init(Native Method)
        at sun.nio.ch.FileDispatcherImpl.<clinit>(FileDispatcherImpl.java:35)
        ... 16 more
```

The Docker on LXD container follows the requirements of the Ubuntu document, and the Docker container can be in privileged mode!
If privileged mode is enabled, the fault will disappear during manual execution, so I have reason to suspect that the construction of this package must enable privileged mode

**To Reproduce**
N/A 
As described above

**Expected behavior**
Compile normally without modifying dockerfile

**Screenshots**
N/a

**Version of Kapua**
1.9.10

**Type of deployment**
[x] Docker -  Docker on LXD
[ ] Openshift (in its variants)
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**

**Comment by jack9603301** [comment]
Okay, this seems to be an issue with Docker on LXD, sorry for contaminating the issues
